### ISSUE TITLE
Crear Producto Proveedor 

### ISSUE THREAD

**Issue by Tikiram** [oiramalli/sa-proyecto#5]
Crear Producto Cliente : En la tabla de propiedades se tiene `precio_venta` pero en los ejemplos se envia `precio`, cual se va a utilizar `precio_venta` o `precio`?

```json
{
  "id_proveedor": 24,
  "nombre": "Monitor LGU32",
  "descripcion": "Monitor LG de 32 pulgadas 4k@240HZ",
  "stock": 50,
  "precio": 2000,
  "foto": "https://www.lg.com/us/images/monitors/md05602277/gallery/1100-1.jpg"
}
```

**Comment by oiramalli** [comment]
Gracias @Tikiram Ya se corrigió el error. 

Se corrigió en e879877d718826e81e1cbcb06dcf455bd014f2a7 
(El mensaje del commit está malo)

Se utilizará `precio_venta`
